project:
  type: website
  output-dir: docs

website:
    google-analytics: "G-PM1MXTXH7M"
    title: Lucas da Silva
    search: false  
    favicon: img/favicon.png
    back-to-top-navigation: false
    navbar:
      pinned: true
      title: false
      left:
        - href: index.qmd
          text: Sobre
        - href: cv/index.qmd
          text: Currículo
        - href: projects/index.qmd
          text: Projetos
        - href: blog/index.qmd
          text: Blog
      right: 
        - icon: linkedin
          href: https://www.linkedin.com/in/luc-dasilva/
          target: _blank
        - icon: github
          href: https://github.com/luc-dasilva
          target: _blank
        - icon: envelope-fill
          href: mailto:lucasgomes.wdcs@gmail.com
          target: _blank

format:
  html:
    theme: theming/styles.scss
    anchor-sections: false
    title-block-banner: false
    code-link: true
    mainfont: "JetBrains Mono, JetBrainsMono Nerd Font Mono, Cascadia Code, monospace"
    monofont: "JetBrains Mono, JetBrainsMono Nerd Font Mono, Cascadia Code, monospace"
    toc: false
    toc-depth: 1
    lang: pt-BR
    monobackgroundcolor: "#151515"
    code-copy: hover
    include-after-body:
      - theming/navbar-active.html

editor: source