project:
  type: website
  output-dir: docs

website:
    google-analytics: "G-PM1MXTXH7M"
    title: Lucas da Silva
    search: false  
    favicon: img/favicon.png
    back-to-top-navigation: false
    navbar:
      # logo: img/favicon.png
      pinned: true
      title: false
      left:
        - href: index.qmd
          text: Sobre mim
        - href: cv/cv_lucas.pdf
          text: Currículo
          target: _blank
        - href: https://luc-dasilva.shinyapps.io/indb3/
          text: IndB3
          target: _blank
        - href: blog/index.qmd
          text: Blog
      right: 
        - icon: linkedin
          href: https://www.linkedin.com/in/luc-dasilva/
          target: _blank
        - icon: github
          href: https://github.com/luc-dasilva
          target: _blank
        - icon: envelope-fill
          href: mailto:lucasgomes.wdcs@gmail.com
          target: _blank

format:
  html:
    theme: theming/styles.scss
    title-block-banner: true
    code-link: true
    mainfont:  "Lato, Open Sans, sans-serif"
    monofont: "Source Code Pro, Consolas, monospace"
    toc: false
    lang: pt-BR
    monobackgroundcolor: "#EDEFF1"
    code-copy: hover

editor: source

