project:
  type: website
  output-dir: docs

website:
    title: Lucas da Silva
    search: false  
    favicon: images/favicon.png
    navbar:
      pinned: true
      title: false
      left:
        - href: index.qmd
          text: Sobre mim
        - href: cv/cv.pdf
          text: Currículo
          target: _blank
        - text: Projetos
          menu: 
            - text: Projeto 1
              href: projects/proj1.qmd
            - text: Projeto 2
              href: projects/proj2.qmd
        - href: blog/index.qmd
          text: Blog
      right: 
        - icon: linkedin
          href: https://www.linkedin.com
          target: _blank
        - icon: github
          href: https://github.com/luc-dasilva
          target: _blank
        - icon: envelope-fill
          href: mailto:lucasgomes.wdcs@gmail.com
          target: _blank
        # - icon: translate
        #   href: index_en.qmd
    # page-footer:
    #   background: light
    #   left: Lucas da Silva, 2024.
    #   right: Este website é feito com [Quarto.](https://quarto.org/){target=_blank}


format:
  html:
    theme: styles.scss
    title-block-banner: true
    mainfont: Source Sans 3
    toc: false
    lang: pt-BR
    monofont: 'Source Code Pro'
    code-copy: hover
    # grid: 
    #   sidebar-width: 200px
    #   margin-width: 200px

editor: visual

